#!/usr/bin/env bash
# Function to display DNS information for a subdomain

get_dns_info() {
  subdomain=$1
  domain=$2

  dns_info=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:')


  subdomain_record_type=$(echo "${dns_info}" | awk '/IN/{print $4}')
  subdomain_destination=$(echo "${dns_info}" | awk '/IN/{print $5}')

  echo "The subdomain ${subdomain} is a ${subdomain_record_type} record and points to ${subdomain_destination}"
}

if [ $# -eq 1 ]; then
  get_dns_info "www" "$1"
  get_dns_info "100.26.247.12" "$1"
  get_dns_info "34.224.15.177" "$1"
  get_dns_info "18.233.63.177" "$1"
elif [ $# -eq 2 ]; then
  get_dns_info "$2" "$1"
else
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi
