#!/usr/bin/env bash
# Function to display DNS information for a subdomain

dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "100.26.247.12"
  dns_config "$1" "34.224.15.177"
  dns_config "$1" "18.233.63.177"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
