#!/usr/bin/env bash
# 1-install_nginx_web_server


# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Replace the default Nginx configuration with a simple configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 'Hello World!';
    }

}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
