#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Modify the Nginx configuration to include a custom 404 page
sudo sed -i '/error_page 404 \/404.html;/a \\tlocation = /404.html {\n\t\treturn 404 \"Ceci n\'est pas une page\";\n\t}' /etc/nginx/sites-available/default

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
