#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Modify the Nginx configuration to include a custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 'Hello World!';
    }

    error_page 404 /404.html;
    location = /404.html {
        return 404 'Ceci n\'est pas une page';
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
