#!/usr/bin/env bash
# This script configures Nginx with a custom HTTP header X-Served-By

# Update the package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Add custom header configuration to Nginx
# Note: Assuming line 47 is where the server block starts in the default Nginx configuration file
sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Create sample HTML files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Start Nginx service
sudo service nginx start
