#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server

# Update package list
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Edit config file
server_config=\
"
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server  57446-web-01 18.204.16.29:80 check
    server  57446-web-02 54.90.56.254:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy to apply the changes
sudo service haproxy restart
