#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend web_frontend
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    mode http
    balance roundrobin
    server  57446-web-01 18.204.16.29:80 check
    server  57446-web-02 54.90.56.254:80 check
EOF

# Restart HAProxy to apply the changes
sudo service haproxy restart
