#!/usr/bin/env bash
# Ping IP address passed as argument 5 times


# Check if an argument (IP address) is provided
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the first argument
ip_address="$1"

# Perform the ping operation five times and display the results
ping -c 5 "$ip_address"
