#!/usr/bin/env bash
# This script manages 'manage_my_process'


# Check for root privilege
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root."
    exit 1
fi

# Check for the correct number of arguments
if [ $# -ne 1 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

# Define the path to the manage_my_process script
MANAGE_SCRIPT="/home/fazzy/alx-system_engineering-devops/0x05-processes_and_signals/manage_my_process"

# Check the command-line argument
case "$1" in
    start)
        $MANAGE_SCRIPT start
        ;;
    stop)
        $MANAGE_SCRIPT stop
        ;;
    restart)
        $MANAGE_SCRIPT restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
