#!/usr/bin/env bash
# Kills the 4-to_infinity_and_beyond process


# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")


    # If the process is running, terminate it
    kill "$pid"
    echo "Terminated"