#!/usr/bin/env bash
# This script will read the file /etc/passwd and print the username, user ID, and home directory of each user


# Read the /etc/passwd file line by line
while IFS=':' read -r username password uid gid info home shell
do 
    # Display the user information in the specified format
     echo "The user $username is part of the $gid gang,"\
      "lives in $home and rides $shell."\
      "$uid's place is protected by the passcode $password,"\
      "more info about the user here: $info"
done < /etc/passwd
