#!/usr/bin/env bash
# This script checks if a file exists and if it is empty

# Set the filename to check
file_name="school"

# Check if the file exists
if [ -e "$file_name" ]
then
    echo "school file exists"
    
    # Check if the file is not empty
    if [ -s "$file_name" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    # Check if the file is a regular file
    if [ -f "$file_name" ]
    then
        echo "school is a regular file"
    fi
else
    # If the file doesn't exist, print this message
    echo "school file does not exist"
fi
