#!/usr/bin/env bash
# Bash script to create an RSA key pair

# Define key file names
private_key="school"
public_key="$private_key.pub"

# Generate RSA key pair with a passphrase
ssh-keygen -t rsa -b 4096 -f "$private_key" -N "betty"
